[package]
name = "intro_df"
version = "0.0.1"

[dependencies]

Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/devnet" }
Capy = { git = "https://github.com/MystenLabs/sui.git", subdir = "sui/capy", rev = "framework/devnet" }

[addresses]
intro_df =  "0x0"
sui =  "0x2"
capy = "0x0"
